name: httper
description: A dart package can help you use http library easily. Provides generics's models and callbacks for 200/400/401/404/500/Error/Others.
version: 1.0.1
repository: https://github.com/billcoding/dart_httper

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  http: ^1.2.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
